// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Flowbit.Infrastructure.Data;
using Flowbit.Shared.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flowbit.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260722190109_MoveFlowbitObjectsToSchema")]
    partial class MoveFlowbitObjectsToSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("flowbit")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.EngineSettingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Namespace")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Namespace", "Key")
                        .IsUnique();

                    b.ToTable("engine_settings", "flowbit");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.ExecutionTokenEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FaultCode")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("FaultDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("InstanceId")
                        .HasColumnType("bigint");

                    b.Property<string>("NodeExternalId")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("NodeId")
                        .HasColumnType("integer");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId", "Id")
                        .IsDescending(false, true);

                    b.HasIndex("InstanceId", "Status");

                    b.HasIndex("NodeExternalId", "Status");

                    b.HasIndex("NodeId", "Status");

                    b.ToTable("execution_tokens", "flowbit");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.InstanceHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("ActionId")
                        .HasColumnType("integer");

                    b.Property<int>("FromStepId")
                        .HasColumnType("integer");

                    b.Property<long>("InstanceId")
                        .HasColumnType("bigint");

                    b.Property<int?>("ItemIndex")
                        .HasColumnType("integer");

                    b.Property<long?>("MultiInstanceExecutionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<JsonDocument>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("PerformedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("ToStepId")
                        .HasColumnType("integer");

                    b.Property<long?>("TokenId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserTaskId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.ToTable("instance_history", "flowbit");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.InstanceVariableEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("InstanceId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("SetAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SetBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("SourceActionId")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("VariableName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("VariableName", "InstanceId");

                    b.HasIndex("InstanceId", "VariableName", "Id")
                        .IsDescending(false, false, true);

                    b.ToTable("instance_variables", "flowbit");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.MessageDeliveryReceiptEntity", b =>
                {
                    b.Property<long>("InstanceId")
                        .HasColumnType("bigint");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .UseCollation("C");

                    b.Property<string>("CorrelationHeaderName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<byte[]>("CredentialProofHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("CredentialProofSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("EnvelopeProofHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("EnvelopeProofSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<short>("ProofVersion")
                        .HasColumnType("smallint");

                    b.Property<int>("SourceNodeId")
                        .HasColumnType("integer");

                    b.Property<long>("WaitHistoryId")
                        .HasColumnType("bigint");

                    b.HasKey("InstanceId", "IdempotencyKey");

                    b.HasIndex("WaitHistoryId")
                        .IsUnique();

                    b.ToTable("message_delivery_receipts", "flowbit");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.MultiInstanceExecutionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CancelledCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("integer");

                    b.Property<string>("CompletionReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("InstanceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("NodeId")
                        .HasColumnType("integer");

                    b.Property<bool>("OnePerActor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ResultVariable")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("TokenId")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("WinningFlowId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId", "Status");

                    b.HasIndex("TokenId", "NodeId", "Status");

                    b.ToTable("multi_instance_executions", "flowbit");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.MultiInstanceFlowCountEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CompletedCount")
                        .HasColumnType("integer");

                    b.Property<long>("ExecutionId")
                        .HasColumnType("bigint");

                    b.Property<int>("FlowId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId", "FlowId")
                        .IsUnique();

                    b.ToTable("multi_instance_flow_counts", "flowbit");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.SequenceFlowOccurrenceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("InstanceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAction")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTraversal")
                        .HasColumnType("boolean");

                    b.Property<int?>("ItemIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long?>("MultiInstanceExecutionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("SequenceFlowId")
                        .HasColumnType("integer");

                    b.Property<int>("SourceNodeId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetNodeId")
                        .HasColumnType("integer");

                    b.Property<long?>("TokenId")
                        .HasColumnType("bigint");

                    b.Property<string>("User")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.PrimitiveCollection<List<string>>("UserRoles")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<long?>("UserTaskId")
                        .HasColumnType("bigint");

                    b.Property<JsonDocument>("ValuesJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("UserTaskId")
                        .IsUnique()
                        .HasFilter("\"UserTaskId\" IS NOT NULL AND \"IsAction\"");

                    b.HasIndex("InstanceId", "SequenceFlowId", "Id")
                        .IsDescending(false, false, true);

                    b.ToTable("sequence_flow_occurrences", "flowbit", t =>
                        {
                            t.HasCheckConstraint("CK_sequence_flow_occurrences_action_or_traversal", "\"IsAction\" OR \"IsTraversal\"");
                        });
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.SequenceFlowSummaryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActionCount")
                        .HasColumnType("bigint");

                    b.Property<long>("InstanceId")
                        .HasColumnType("bigint");

                    b.Property<string>("LastActionKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("LastActionOccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastActionUser")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.PrimitiveCollection<List<string>>("LastActionUserRoles")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<JsonDocument>("LastActionValuesJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("LastTraversalKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("LastTraversalOccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastTraversalUser")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.PrimitiveCollection<List<string>>("LastTraversalUserRoles")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<JsonDocument>("LastTraversalValuesJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("SequenceFlowId")
                        .HasColumnType("integer");

                    b.Property<long>("TraversalCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId", "SequenceFlowId")
                        .IsUnique();

                    b.ToTable("sequence_flow_summaries", "flowbit");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.UserTaskEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Assignee")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.PrimitiveCollection<List<string>>("CompletedByRoles")
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("InstanceId")
                        .HasColumnType("bigint");

                    b.Property<int?>("ItemIndex")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("ItemValueJson")
                        .HasColumnType("jsonb");

                    b.Property<long?>("MultiInstanceExecutionId")
                        .HasColumnType("bigint");

                    b.Property<string>("NodeExternalId")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("NodeId")
                        .HasColumnType("integer");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("RequiresAssignment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("RequiresClaim")
                        .HasColumnType("boolean");

                    b.Property<JsonDocument>("ResultJson")
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<List<string>>("Roles")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<int?>("SelectedFlowId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("TokenId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Roles");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Roles"), "gin");

                    b.HasIndex("TokenId");

                    b.HasIndex("InstanceId", "Status");

                    b.HasIndex("MultiInstanceExecutionId", "ItemIndex")
                        .IsUnique();

                    b.HasIndex("NodeExternalId", "Status");

                    b.HasIndex("NodeId", "Status");

                    b.HasIndex("MultiInstanceExecutionId", "Status", "ItemIndex");

                    b.HasIndex("Status", "CreatedAt", "Id");

                    b.HasIndex("Status", "UpdatedAt", "Id");

                    b.HasIndex("InstanceId", "Status", "CompletedAt", "Id");

                    b.ToTable("user_tasks", "flowbit");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.WorkflowBusinessKeyClaimEntity", b =>
                {
                    b.Property<string>("WorkflowKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("BusinessKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .UseCollation("C");

                    b.Property<long?>("ActiveInstanceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPermanent")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastInstanceId")
                        .HasColumnType("bigint");

                    b.HasKey("WorkflowKey", "BusinessKey");

                    b.HasIndex("ActiveInstanceId");

                    b.HasIndex("LastInstanceId");

                    b.ToTable("workflow_business_key_claims", "flowbit");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.WorkflowBusinessKeyScopeEntity", b =>
                {
                    b.Property<string>("WorkflowKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("ActivatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("WorkflowKey");

                    b.ToTable("workflow_business_key_scopes", "flowbit");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.WorkflowDefinitionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<WorkflowModel>("Definition")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<string>("WorkflowKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("Definition");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Definition"), "gin");

                    b.HasIndex("WorkflowKey");

                    b.HasIndex("WorkflowKey", "Version")
                        .IsUnique();

                    b.ToTable("workflow_definitions", "flowbit");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.WorkflowIdempotencyClaimEntity", b =>
                {
                    b.Property<string>("WorkflowKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .UseCollation("C");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("InstanceId")
                        .HasColumnType("bigint");

                    b.HasKey("WorkflowKey", "IdempotencyKey");

                    b.HasIndex("InstanceId")
                        .IsUnique();

                    b.ToTable("workflow_idempotency_claims", "flowbit");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.WorkflowInstanceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BusinessKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .UseCollation("C");

                    b.Property<string>("BusinessKeyUniqueness")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .UseCollation("C");

                    b.Property<string>("StartedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("WorkflowDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkflowKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDefinitionId");

                    b.HasIndex("CreatedAt", "Id");

                    b.HasIndex("UpdatedAt", "Id");

                    b.HasIndex("WorkflowKey", "IdempotencyKey");

                    b.HasIndex("Status", "UpdatedAt", "Id");

                    b.HasIndex("WorkflowKey", "BusinessKey", "Status");

                    b.ToTable("workflow_instances", "flowbit");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.WorkflowSettingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Namespace")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<JsonElement>("Value")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Namespace", "Name")
                        .IsUnique();

                    b.ToTable("workflow_settings", "flowbit");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.ExecutionTokenEntity", b =>
                {
                    b.HasOne("Flowbit.Infrastructure.Entities.WorkflowInstanceEntity", "Instance")
                        .WithMany("Tokens")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.InstanceHistoryEntity", b =>
                {
                    b.HasOne("Flowbit.Infrastructure.Entities.WorkflowInstanceEntity", "Instance")
                        .WithMany("History")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.InstanceVariableEntity", b =>
                {
                    b.HasOne("Flowbit.Infrastructure.Entities.WorkflowInstanceEntity", "Instance")
                        .WithMany("Variables")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.MessageDeliveryReceiptEntity", b =>
                {
                    b.HasOne("Flowbit.Infrastructure.Entities.WorkflowInstanceEntity", "Instance")
                        .WithMany("MessageDeliveryReceipts")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flowbit.Infrastructure.Entities.InstanceHistoryEntity", "WaitHistory")
                        .WithMany()
                        .HasForeignKey("WaitHistoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instance");

                    b.Navigation("WaitHistory");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.MultiInstanceExecutionEntity", b =>
                {
                    b.HasOne("Flowbit.Infrastructure.Entities.WorkflowInstanceEntity", "Instance")
                        .WithMany("MultiInstanceExecutions")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flowbit.Infrastructure.Entities.ExecutionTokenEntity", "Token")
                        .WithMany("MultiInstanceExecutions")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instance");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.MultiInstanceFlowCountEntity", b =>
                {
                    b.HasOne("Flowbit.Infrastructure.Entities.MultiInstanceExecutionEntity", "Execution")
                        .WithMany("FlowCounts")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Execution");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.SequenceFlowOccurrenceEntity", b =>
                {
                    b.HasOne("Flowbit.Infrastructure.Entities.WorkflowInstanceEntity", "Instance")
                        .WithMany("SequenceFlowOccurrences")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.SequenceFlowSummaryEntity", b =>
                {
                    b.HasOne("Flowbit.Infrastructure.Entities.WorkflowInstanceEntity", "Instance")
                        .WithMany("SequenceFlowSummaries")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.UserTaskEntity", b =>
                {
                    b.HasOne("Flowbit.Infrastructure.Entities.WorkflowInstanceEntity", "Instance")
                        .WithMany("UserTasks")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flowbit.Infrastructure.Entities.MultiInstanceExecutionEntity", "MultiInstanceExecution")
                        .WithMany("UserTasks")
                        .HasForeignKey("MultiInstanceExecutionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Flowbit.Infrastructure.Entities.ExecutionTokenEntity", "Token")
                        .WithMany("UserTasks")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instance");

                    b.Navigation("MultiInstanceExecution");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.WorkflowBusinessKeyClaimEntity", b =>
                {
                    b.HasOne("Flowbit.Infrastructure.Entities.WorkflowInstanceEntity", null)
                        .WithMany()
                        .HasForeignKey("ActiveInstanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Flowbit.Infrastructure.Entities.WorkflowInstanceEntity", null)
                        .WithMany()
                        .HasForeignKey("LastInstanceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.WorkflowIdempotencyClaimEntity", b =>
                {
                    b.HasOne("Flowbit.Infrastructure.Entities.WorkflowInstanceEntity", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.WorkflowInstanceEntity", b =>
                {
                    b.HasOne("Flowbit.Infrastructure.Entities.WorkflowDefinitionEntity", "WorkflowDefinition")
                        .WithMany("Instances")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Flowbit.Infrastructure.Entities.WorkflowBusinessKeyClaimEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkflowKey", "BusinessKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Flowbit.Infrastructure.Entities.WorkflowIdempotencyClaimEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkflowKey", "IdempotencyKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.ExecutionTokenEntity", b =>
                {
                    b.Navigation("MultiInstanceExecutions");

                    b.Navigation("UserTasks");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.MultiInstanceExecutionEntity", b =>
                {
                    b.Navigation("FlowCounts");

                    b.Navigation("UserTasks");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.WorkflowDefinitionEntity", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("Flowbit.Infrastructure.Entities.WorkflowInstanceEntity", b =>
                {
                    b.Navigation("History");

                    b.Navigation("MessageDeliveryReceipts");

                    b.Navigation("MultiInstanceExecutions");

                    b.Navigation("SequenceFlowOccurrences");

                    b.Navigation("SequenceFlowSummaries");

                    b.Navigation("Tokens");

                    b.Navigation("UserTasks");

                    b.Navigation("Variables");
                });
#pragma warning restore 612, 618
        }
    }
}
